# Generated by Django 2.2 on 2020-01-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioUca', '0002_auto_20200117_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariouca',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuariouca',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
