# Generated by Django 2.2 on 2019-11-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioUca', '0002_estudiante_pass_profesor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuariouca',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuariouca',
            name='username',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso_max',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AlterField(
            model_name='usuariouca',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariouca',
            name='nif',
            field=models.CharField(default=32085090, max_length=8, unique=True),
        ),
    ]
