# Generated by Django 2.2.7 on 2019-11-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Censo', '0002_auto_20191126_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censo',
            name='id_usuario',
        ),
    ]
