# Generated by Django 2.0 on 2019-12-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Censo', '0004_auto_20191126_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censo',
            name='id_votacion',
        ),
    ]
