# Generated by Django 2.2 on 2019-11-19 22:45

import VotacionesUca.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacione',
            fields=[
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='VotacionesUca.ProcesoElectoral')),
                ('esPresencial', models.BooleanField(default=False)),
                ('votoRectificable', models.BooleanField(default=False)),
                ('tipoVotacion', models.IntegerField(choices=[(0, 'SIMPLE'), (1, 'COMPLEJA')], default=VotacionesUca.models.tipoV(0))),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Votacion',
        ),
        migrations.AddField(
            model_name='votacione',
            name='pregunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='VotacionesUca.Pregunta'),
        ),
    ]
