# Generated by Django 2.0 on 2019-12-18 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoelectoral',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2019, 12, 18, 8, 44, 53, 569630, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='procesoelectoral',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 12, 18, 8, 44, 53, 569606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='procesoelectoral',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='procesoelectoral',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
