# Generated by Django 2.0 on 2019-12-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='max_vacantes',
            field=models.FloatField(default=0.7),
        ),
    ]
