# Generated by Django 2.2 on 2020-01-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariovotacion',
            name='Pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotacionesUca.Pregunta'),
        ),
        migrations.AlterField(
            model_name='usuariovotacion',
            name='Votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotacionesUca.Votacion'),
        ),
    ]
