# Generated by Django 2.2 on 2019-11-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacione',
            fields=[
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='VotacionesUca.ProcesoElectoral')),
                ('esPresencial', models.BooleanField(default=False)),
                ('votoRectificable', models.BooleanField(default=False)),
                ('tipoVotacion', models.IntegerField(verbose_name=1)),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='VotacionesUca.Pregunta')),
            ],
        ),
        migrations.DeleteModel(
            name='Votacion',
        ),
    ]
