# Generated by Django 2.0 on 2019-12-18 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0002_auto_20191218_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoelectoral',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2019, 12, 18, 8, 46, 9, 554162, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='procesoelectoral',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 12, 18, 8, 46, 9, 554137, tzinfo=utc)),
        ),
    ]
