# Generated by Django 2.2 on 2019-11-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0002_auto_20191119_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='procesoelectoral',
            options={'verbose_name': 'Proceso Electoral', 'verbose_name_plural': 'Procesos Electorales'},
        ),
        migrations.AlterModelOptions(
            name='votacione',
            options={'verbose_name': 'Votación', 'verbose_name_plural': 'Votaciones'},
        ),
        migrations.AddField(
            model_name='procesoelectoral',
            name='nombreFicheroCenso',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='procesoelectoral',
            name='esConsulta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='votacione',
            name='esPresencial',
            field=models.BooleanField(default=False, verbose_name='Presencial'),
        ),
        migrations.AlterField(
            model_name='votacione',
            name='votoRectificable',
            field=models.BooleanField(default=False, verbose_name='Habilitar voto rectificable'),
        ),
    ]
