# Generated by Django 2.0 on 2019-12-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0002_auto_20191223_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='max_candidatos',
            field=models.IntegerField(default=2),
        ),
    ]
