# Generated by Django 2.2 on 2019-11-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0002_auto_20191119_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacione',
            name='tipoVotacion',
            field=models.IntegerField(choices=[(0, 'SIMPLE'), (1, 'COMPLEJA')]),
        ),
    ]
