# Generated by Django 2.2 on 2019-11-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0003_auto_20191120_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoelectoral',
            name='esConsulta',
            field=models.BooleanField(default=False, verbose_name='Consulta'),
        ),
    ]
