# Generated by Django 2.0 on 2019-12-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0003_auto_20191218_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoelectoral',
            name='hora_fin',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='procesoelectoral',
            name='hora_inicio',
            field=models.TimeField(auto_now=True),
        ),
    ]
