# Generated by Django 2.2 on 2020-01-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0003_auto_20200112_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioeleccion',
            name='Eleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotacionesUca.Eleccion'),
        ),
        migrations.AlterField(
            model_name='usuarioeleccion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariovotacion',
            name='Pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotacionesUca.Pregunta'),
        ),
        migrations.AlterField(
            model_name='usuariovotacion',
            name='Votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotacionesUca.Votacion'),
        ),
        migrations.AlterField(
            model_name='usuariovotacion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
