# Generated by Django 2.0 on 2019-12-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Censo', '0001_initial'),
        ('VotacionesUca', '0004_auto_20191218_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='censo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Censo.Censo'),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='censo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Censo.Censo'),
        ),
    ]
