# Generated by Django 2.2 on 2019-11-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0005_auto_20191119_1851'),
        ('VotacionesUca', '0004_auto_20191120_0846'),
    ]

    operations = [
    ]
