# Generated by Django 2.0 on 2019-12-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0005_auto_20191218_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoelectoral',
            name='nombre_fichero_censo',
        ),
    ]
