# Generated by Django 2.2 on 2020-01-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0005_auto_20200116_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opcionescompleja',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personas',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='enunciado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarioeleccion',
            name='seleccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuariovotacion',
            name='seleccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
