# Generated by Django 2.0 on 2019-12-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0006_remove_procesoelectoral_nombre_fichero_censo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votacion',
            old_name='max_elector',
            new_name='max_respuestas',
        ),
    ]
