# Generated by Django 2.0 on 2019-12-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0007_auto_20191218_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='nombre_votacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
