# Generated by Django 2.0 on 2019-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0008_votacion_nombre_votacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoelectoral',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='procesoelectoral',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
