# Generated by Django 2.0 on 2019-12-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0009_auto_20191218_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoelectoral',
            name='hora_fin',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='procesoelectoral',
            name='hora_inicio',
            field=models.TimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='votacion',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='votacion',
            name='pregunta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='VotacionesUca.Pregunta'),
        ),
    ]
