# Generated by Django 2.0 on 2019-12-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionesUca', '0012_auto_20191218_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='voto_restringido',
            field=models.BooleanField(default=False),
        ),
    ]
